/**
 * Bundles the ariaTree module into a self-contained script string
 * that can be injected into browser pages via page.evaluate().
 *
 * Usage: tsx scripts/bundle-aria-tree.ts
 * Output: src/browser/ariaTree/bundle.ts
 */

import { build } from "esbuild";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, "..");

async function main() {
  // Bundle the ariaTree entry point into a single IIFE
  const result = await build({
    entryPoints: [join(projectRoot, "src/browser/ariaTree/ariaSnapshot.ts")],
    bundle: true,
    format: "iife",
    globalName: "__sparkAriaTree",
    write: false,
    minify: false,
    target: "es2022",
    platform: "browser",
  });

  let bundledCode = result.outputFiles[0].text;

  // The IIFE creates `var __sparkAriaTree = (...)()` which is local when run
  // inside `new Function()`. Append an explicit globalThis assignment so the
  // injected script works regardless of execution context.
  bundledCode += "\nglobalThis.__sparkAriaTree = __sparkAriaTree;\n";

  // Wrap in a module that exports the bundled code as a string constant
  const output = `// AUTO-GENERATED by scripts/bundle-aria-tree.ts — do not edit
// Regenerate with: pnpm run bundle:aria
export const ARIA_TREE_SCRIPT = ${JSON.stringify(bundledCode)};
`;

  const outPath = join(projectRoot, "src/browser/ariaTree/bundle.ts");
  writeFileSync(outPath, output);
  console.log(`Wrote ${outPath} (${bundledCode.length} bytes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
